// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx_SDvYeTEB6Ex1KFuz5kdA54j7klp0-U',
    appId: '1:884690146423:android:86a376ab0a92954955e272',
    messagingSenderId: '884690146423',
    projectId: 'carswap-16847',
    storageBucket: 'carswap-16847.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvui1qmqS_KBCrFjOO5zpq9AeGx1T2MDk',
    appId: '1:884690146423:ios:c5f148cc46e0890955e272',
    messagingSenderId: '884690146423',
    projectId: 'carswap-16847',
    storageBucket: 'carswap-16847.appspot.com',
    iosBundleId: 'com.example.carline',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQHZXskSPLL9gVzdqZa8Od0aDeuFpHq0I',
    appId: '1:884690146423:web:2f8decaa7e5636df55e272',
    messagingSenderId: '884690146423',
    projectId: 'carswap-16847',
    authDomain: 'carswap-16847.firebaseapp.com',
    storageBucket: 'carswap-16847.appspot.com',
    measurementId: 'G-5SK8TVRCRN',
  );

}